# Generated by Django 4.2.3 on 2023-08-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEsportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CentroEsportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centers.centroesportivo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('CentroEsportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centers.centroesportivo')),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centers.quadra')),
            ],
        ),
    ]
