# Generated by Django 4.2.3 on 2023-09-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quadra',
            name='centro_esportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centers.centroesportivo'),
        ),
        migrations.AddField(
            model_name='quadra',
            name='tipos_esporte',
            field=models.ManyToManyField(to='sports_centers.tipoesporte'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='centro_esportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_centers.centroesportivo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centroesportivo',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
