# Generated by Django 4.2.3 on 2023-09-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_centers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroesportivo',
            name='resumo_comentarios',
            field=models.TextField(blank=True),
        ),
    ]
